const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const context = vm.createContext({ Intl });
for (const file of ['menuData.js', 'orderCore.js', 'orders.js', 'cash.js']) {
  vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'js', file), 'utf8'), context);
}
const { AmorPOS: pos, AmorOrders: orders, AmorCash: cash } = context;
const clone = value => JSON.parse(JSON.stringify(value));
const apertura = '2026-10-06T13:00:00.000Z';
const cobro1 = '2026-10-06T14:00:00.000Z';
const cobro2 = '2026-10-06T14:01:00.000Z';
const cierre = '2026-10-06T20:00:00.000Z';
assert.equal(cash.montoACentavos('10,05'), 1005);
assert.equal(cash.montoACentavos('0.01'), 1);
assert.equal(cash.montoACentavos('999999.99'), 99999999);
for (const invalid of ['1.001', '-5', '1,234.56', '1e2', '', '0', '1000000', 'NaN']) {
  assert.throws(() => cash.montoACentavos(invalid));
}
assert.equal(cash.abrirCaja(cash.cajaVacia(), '0', apertura).fondoInicialCentavos, 0);
assert.equal(cash.normalizarCaja(undefined).abierta, false);
assert.throws(() => cash.normalizarCaja({ ...cash.cajaVacia(), fondoInicialCentavos: 1 }), /cero/);
const vacia = cash.cajaVacia();
let caja = cash.abrirCaja(vacia, '100.25', apertura);
assert.equal(vacia.abierta, false);
assert.throws(() => cash.abrirCaja(caja, '200', apertura), /abierto/);
assert.throws(() => cash.registrarGasto(vacia, '1', 'Hielo', cobro1), /Abre/);
const food = { ...pos.crearPartida('chilaquiles-con-pollo-o-huevo', { salsa: 'roja', proteina: 'pollo', extras: ['huevo', 'pollo'] }), cantidad: 2 };
const coffee = pos.crearPartida('cafe-americano', { extras: ['leche-deslactosada', 'shot-de-espresso'] });
let pedido = orders.nuevoPedido([food, coffee], 'Mesa 3', 1, apertura);
assert.throws(() => cash.cobrarPartidas(pedido, 'todos', vacia, 'efectivo', cobro1), /Abre/);
assert.throws(() => cash.cobrarPartidas(pedido, 'todos', caja, '', cobro1), /Selecciona/);
assert.throws(() => cash.cobrarPartidas(pedido, 'todos', caja, 'tarjeta', '2026-10-06T12:59:00Z'), /fecha/);
const originalPedido = JSON.stringify(pedido);
const originalCaja = JSON.stringify(caja);
let resultado = cash.cobrarPartidas(pedido, pedido.partidas[0].id, caja, 'efectivo', cobro1);
assert.equal(JSON.stringify(pedido), originalPedido);
assert.equal(JSON.stringify(caja), originalCaja);
assert.equal(resultado.montoCentavos, 46000);
pedido = resultado.pedido; caja = resultado.caja;
assert.equal(pedido.partidas[0].metodoPago, 'efectivo');
assert.equal(pedido.partidas[0].turnoId, caja.turnoId);
assert.equal(pedido.partidas[1].pagado, false);
assert.throws(() => cash.cobrarPartidas(pedido, pedido.partidas[0].id, caja, 'efectivo', cobro2), /ya están pagados/);
resultado = cash.cobrarPartidas(pedido, 'todos', caja, 'tarjeta', cobro2);
assert.equal(resultado.montoCentavos, 10000); // El cobro total restante no cuenta otra vez el pago parcial.
pedido = resultado.pedido; caja = resultado.caja;
assert.equal(pedido.estado, 'PAGADO');
assert.equal(pedido.partidas[0].pagadoEn, cobro1);
assert.equal(caja.pagos.length, 2);
assert.throws(() => cash.cobrarPartidas(pedido, 'todos', caja, 'efectivo', cobro2), /ya están pagados/);
caja = cash.registrarGasto(caja, '20,10', ' Compra de hielo ', '2026-10-06T15:00:00Z');
assert.equal(caja.gastosDelDia[0].concepto, 'Compra de hielo');
assert.throws(() => cash.registrarGasto(caja, '0', 'Hielo', cobro2), /monto/);
assert.throws(() => cash.registrarGasto(caja, '1', '  ', cobro2), /concepto/);
const resumen = cash.resumirCaja(caja);
assert.equal(resumen.fondoInicialCentavos, 10025);
assert.equal(resumen.ventasEfectivoCentavos, 46000);
assert.equal(resumen.ventasTarjetaCentavos, 10000);
assert.equal(resumen.gastosExtrasCentavos, 2010);
assert.equal(resumen.efectivoEsperadoCentavos, 54015);
assert.equal(resumen.totalVentasCentavos, 56000);
assert.throws(() => cash.registrarGasto(caja, '540.16', 'Proveedor', cobro2), /excede/);
assert.equal(cash.validarVinculos([pedido], caja, []), true);
const pagoTampered = clone(caja); pagoTampered.pagos[0].importeCentavos--;
assert.throws(() => cash.validarVinculos([pedido], pagoTampered, []), /importe/);
const pedidoTampered = clone(pedido); pedidoTampered.partidas[0].metodoPago = 'tarjeta';
assert.throws(() => cash.validarVinculos([pedidoTampered], caja, []), /coincide/);
const pagoRepetido = clone(caja); pagoRepetido.pagos.push({ ...pagoRepetido.pagos[0], id: 'pago-duplicado' });
assert.throws(() => cash.normalizarCaja(pagoRepetido), /más de una vez/);
assert.throws(() => cash.cerrarCaja(caja, cobro2), /posteriores/);
const cajaAntesDeCierre = JSON.stringify(caja);
const { caja: cerrada, corte } = cash.cerrarCaja(caja, cierre);
assert.equal(JSON.stringify(caja), cajaAntesDeCierre);
assert.equal(cerrada.abierta, false);
assert.equal(cerrada.pagos.length, 0);
assert.equal(cerrada.gastosDelDia.length, 0);
assert.equal(cash.resumirCaja(cerrada).efectivoEsperadoCentavos, 0);
assert.equal(corte.totalVentasCentavos, 56000);
assert.equal(corte.efectivoEsperadoCentavos, 54015);
assert.equal(cash.validarVinculos([pedido], cerrada, [corte]), true);
assert.throws(() => cash.normalizarCorte({ ...corte, totalVentasCentavos: 56001 }), /inconsistentes/);
assert.throws(() => cash.validarVinculos([pedido], cerrada, [corte, corte]), /repetidos/);
assert.throws(() => cash.validarVinculos([pedido], cerrada, []), /movimiento/);
const siguiente = cash.abrirCaja(cerrada, '50', '2026-10-07T13:00:00Z');
assert.equal(cash.resumirCaja(siguiente).totalVentasCentavos, 0);
assert.equal(cash.validarVinculos([pedido], siguiente, [corte]), true);
let legacy = orders.nuevoPedido([coffee], 'Pago anterior', 2, apertura);
legacy = orders.marcarPartida(legacy, 'todos', 'pagado', cobro1);
assert.equal(cash.validarVinculos([legacy], cash.cajaVacia(), []), true);
assert.equal(cash.resumirCaja(siguiente).ventasTarjetaCentavos, 0);
// El importe cobrado en tarjeta nunca permite sacar ese dinero como efectivo.
let soloTarjeta = cash.abrirCaja(cash.cajaVacia(), '0', apertura);
const ticketTarjeta = orders.nuevoPedido([coffee], '', 3, apertura);
soloTarjeta = cash.cobrarPartidas(ticketTarjeta, 'todos', soloTarjeta, 'tarjeta', cobro1).caja;
assert.throws(() => cash.registrarGasto(soloTarjeta, '0.01', 'Hielo', cobro2), /excede/);

// Persistencia real: pago + caja y cierre + corte se escriben como un único expediente.
const data = new Map();
let failWrite = false;
context.localStorage = {
  getItem: key => data.get(key) ?? null,
  setItem: (key, value) => {
    if (failWrite) throw new Error('QuotaExceededError');
    data.set(key, value);
  }
};
for (const file of ['history.js', 'storage.js']) {
  vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'js', file), 'utf8'), context);
}
const storage = context.AmorStorage;
let expediente = storage.vacio();
expediente.pedidos = [orders.nuevoPedido([food, coffee], 'Persistencia', 10, apertura)];
expediente.caja = cash.abrirCaja(expediente.caja, '100', apertura);
expediente = storage.guardarExpediente(expediente);
const stale = clone(expediente);
const antesDelPago = data.get(storage.KEY);
let siguienteExpediente = clone(expediente);
const cobroPersistente = cash.cobrarPartidas(siguienteExpediente.pedidos[0], 'todos', siguienteExpediente.caja, 'efectivo', cobro1);
siguienteExpediente.pedidos[0] = cobroPersistente.pedido;
siguienteExpediente.caja = cobroPersistente.caja;
failWrite = true;
assert.throws(() => storage.guardarExpediente(siguienteExpediente), /QuotaExceeded/);
assert.equal(data.get(storage.KEY), antesDelPago);
assert.equal(storage.cargarExpediente().pedidos[0].partidas[0].pagado, false);
assert.equal(storage.cargarExpediente().caja.pagos.length, 0);
assert.equal(expediente.revision, 1);
failWrite = false;
expediente = storage.guardarExpediente(siguienteExpediente);
assert.equal(storage.cargarExpediente().pedidos[0].partidas[0].metodoPago, 'efectivo');
assert.equal(storage.cargarExpediente().caja.pagos.length, 1);
const antesDelCorte = data.get(storage.KEY);
siguienteExpediente = clone(expediente);
const cortePersistente = cash.cerrarCaja(siguienteExpediente.caja, cierre);
siguienteExpediente.caja = cortePersistente.caja;
siguienteExpediente.historialCortes.push(cortePersistente.corte);
failWrite = true;
assert.throws(() => storage.guardarExpediente(siguienteExpediente), /QuotaExceeded/);
assert.equal(data.get(storage.KEY), antesDelCorte);
assert.equal(storage.cargarExpediente().caja.abierta, true);
assert.equal(storage.cargarExpediente().historialCortes.length, 0);
failWrite = false;
expediente = storage.guardarExpediente(siguienteExpediente);
const recargado = storage.cargarExpediente();
assert.equal(recargado.caja.abierta, false);
assert.equal(recargado.caja.fondoInicialCentavos, 0);
assert.equal(recargado.historialCortes[0].totalVentasCentavos, 56000);
assert.equal(recargado.historialCortes[0].efectivoEsperadoCentavos, 66000);
assert.equal(recargado.pedidos[0].partidas[0].pagado, true);
const despuesDelCorte = data.get(storage.KEY);
assert.throws(() => storage.guardarExpediente(stale), /otra pestaña/);
assert.equal(data.get(storage.KEY), despuesDelCorte);
const legacyState = storage.vacio();
legacyState.pedidos = [legacy];
delete legacyState.caja;
delete legacyState.historialCortes;
const migrated = storage.normalizar(legacyState);
assert.equal(migrated.pedidos[0].partidas[0].pagado, true);
assert.equal(migrated.caja.abierta, false);
assert.equal(cash.resumirCaja(migrated.caja).totalVentasCentavos, 0);
const corteManipulado = clone(recargado);
corteManipulado.historialCortes[0].pagos[0].importeCentavos++;
assert.throws(() => storage.normalizar(corteManipulado), /inconsistentes/);
console.log('✓ Caja, pagos, gastos, cortes, vínculos históricos y persistencia atómica con cuota/revisiones verificados.');
