const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const data = new Map();
let failWrite = false;
const localStorage = {
  getItem: key => data.get(key) ?? null,
  setItem: (key, value) => { if (failWrite) throw new Error('QuotaExceededError'); data.set(key, value); }
};
const context = vm.createContext({ Intl, localStorage });
for (const file of ['menuData.js', 'orderCore.js', 'orders.js', 'history.js', 'cash.js', 'storage.js']) vm.runInContext(fs.readFileSync(path.join(root, 'js', file), 'utf8'), context);
const { AmorPOS: pos, AmorOrders: orders, AmorHistory: history, AmorStorage: storage } = context;
const food = { ...pos.crearPartida('chilaquiles-con-pollo-o-huevo', { salsa: 'roja', proteina: 'pollo', extras: ['huevo', 'pollo'] }), cantidad: 2 };
const coffee = pos.crearPartida('cafe-americano', { extras: ['leche-deslactosada', 'shot-de-espresso'] });
let ticket = orders.nuevoPedido([food, coffee], 'Mesa 03', 1, '2026-10-05T15:00:00Z');
assert.equal(ticket.totalCentavos, 56000);
assert.equal(orders.estaAbierto(ticket), true);
assert.equal(history.resumirDia([ticket], '2026-10-05').totalCentavos, 0);
ticket = orders.marcarPartida(ticket, ticket.partidas[0].id, 'preparado', '2026-10-05T15:05:00Z');
ticket = orders.marcarPartida(ticket, ticket.partidas[0].id, 'pagado', '2026-10-06T05:50:00Z');
const day1 = history.resumirDia([ticket], '2026-10-05');
assert.equal(day1.totalCentavos, 46000);
assert.equal(day1.productos, 2);
assert.equal(day1.categorias.Alimentos, 2);
assert.equal(day1.categorias.Bebidas, 0);
ticket = orders.marcarPartida(ticket, ticket.partidas[0].id, 'pagado', '2026-10-06T06:10:00Z');
assert.equal(ticket.partidas[0].pagadoEn, '2026-10-06T05:50:00Z');
ticket = orders.marcarPartida(ticket, ticket.partidas[1].id, 'pagado', '2026-10-06T06:10:00Z');
assert.equal(ticket.estado, 'PAGADO');
assert.equal(orders.estaAbierto(ticket), true); // Falta preparar el café.
ticket = orders.marcarPartida(ticket, 'todos', 'preparado', '2026-10-06T06:20:00Z');
assert.equal(orders.estaAbierto(ticket), false);
assert.equal(history.fechaLocal('2026-10-06T05:59:00Z'), '2026-10-05');
assert.equal(history.fechaLocal('2026-10-06T06:00:00Z'), '2026-10-06');
const extra = { ...pos.crearExtra('Nuevo producto', '28.55'), cantidad: 3 };
let custom = orders.nuevoPedido([extra], '', 2, '2026-10-06T12:00:00Z');
custom = orders.marcarPartida(custom, 'todos', 'pagado', '2026-10-06T13:00:00Z');
const day2 = history.resumirDia([ticket, custom], '2026-10-06');
assert.equal(day2.totalCentavos, 18565);
assert.equal(day2.productos, 4);
assert.equal(day2.extras, 3);
assert.equal(day2.categorias.Bebidas, 1);
assert.equal(day2.ventas, 2);
const days = history.agruparPorDia([ticket, custom]);
assert.equal(days.length, 2);
assert.equal(days[0].fecha, '2026-10-06');
assert.equal(days[1].fecha, '2026-10-05');
let state = storage.vacio();
state.pedidos = [ticket, custom]; state.siguienteNumero = 3;
state.borrador = { etiqueta: 'Nuevo borrador', partidas: [pos.crearExtra('Extra', '0.01')] };
const stale = JSON.parse(JSON.stringify(state));
state = storage.guardarExpediente(state);
assert.equal(state.revision, 1);
const loaded = storage.cargarExpediente();
assert.equal(loaded.pedidos[0].totalCentavos, 56000);
assert.equal(loaded.siguienteNumero, 3);
assert.equal(loaded.borrador.partidas[0].precioUnitarioCentavos, 1);
assert.throws(() => storage.guardarExpediente(stale), /otra pestaña/);
const before = data.get(storage.KEY);
failWrite = true;
assert.throws(() => storage.guardarExpediente(state), /QuotaExceeded/);
assert.equal(data.get(storage.KEY), before);
failWrite = false;
const tampered = JSON.parse(before);
tampered.pedidos[0].totalCentavos = 1;
assert.throws(() => storage.normalizar(tampered), /inconsistente/);
tampered.pedidos[0].totalCentavos = 56000;
tampered.pedidos.push(tampered.pedidos[0]);
assert.throws(() => storage.normalizar(tampered), /inválido/);
data.set(storage.KEY, '{ corrupto');
assert.throws(() => storage.cargarExpediente());
data.delete(storage.KEY);
data.set('amor-amor-pos:borrador:v1', JSON.stringify({ version: 1, etiqueta: 'Mesa anterior', partidas: [{ productoId: 'waffle-clasico', opciones: { untable: 'Confirmado' }, nota: '', cantidad: 2 }] }));
const migrated = storage.cargarExpediente();
assert.equal(migrated.borrador.etiqueta, 'Mesa anterior');
assert.equal(migrated.borrador.partidas[0].macroCategoria, 'Alimentos');
assert.equal(migrated.borrador.partidas[0].cantidad, 2);
// Añadir el mismo producto mantiene intactos sus cobros y estados anteriores.
const cash = context.AmorCash;
let open = orders.nuevoPedido([food, coffee], 'Mesa 3 · Ana', 3);
let register = cash.abrirCaja(cash.cajaVacia(), '100');
const paid = cash.cobrarPartidas(open, open.partidas[0].id, register, { efectivoRecibido: '500', montoTarjeta: '0' });
open = orders.marcarPartida(paid.pedido, paid.pedido.partidas[0].id, 'preparado');
register = paid.caja;
const beforeAddition = JSON.stringify(open);
const extended = orders.agregarPartidas(open, [food, pos.crearExtra('Postre adicional', '8.40')]);
assert.equal(JSON.stringify(open), beforeAddition);
assert.deepEqual(JSON.parse(JSON.stringify(extended.partidas.slice(0, 2))), JSON.parse(beforeAddition).partidas);
assert.equal(extended.numero, 3);
assert.equal(extended.etiqueta, 'Mesa 3 · Ana');
assert.equal(extended.totalCentavos, 56000 + 46000 + 840);
assert.equal(new Set(extended.partidas.map(p => p.id)).size, 4);
assert.ok(extended.partidas.slice(2).every(p => !p.pagado && !p.preparado && p.pagadoEn === null));
assert.equal(cash.resumirCaja(register, [extended]).ventasEfectivoCentavos, 46000);
assert.equal(history.resumirDia([extended], history.fechaLocal(extended.partidas[0].pagadoEn)).totalCentavos, 46000);
assert.throws(() => orders.agregarPartidas(ticket, [coffee]), /cerrado/);
assert.throws(() => orders.agregarPartidas(open, []), /Agrega productos/);
const additionState = { ...storage.vacio(), pedidos: [extended], caja: register,
  borrador: { etiqueta: 'Próximo pedido', partidas: [coffee] }, adicion: { pedidoId: extended.id, partidas: [extra] } };
const normalizedAddition = storage.normalizar(additionState);
assert.equal(normalizedAddition.adicion.partidas[0].cantidad, 3);
assert.equal(normalizedAddition.borrador.etiqueta, 'Próximo pedido');
assert.throws(() => storage.normalizar({ ...additionState, adicion: { pedidoId: 'pedido-no-existe', partidas: [] } }), /Selección/);

// Una mesa está ocupada hasta preparar y cobrar todas sus partidas; el detalle no permite duplicarla.
assert.equal(orders.claveEtiqueta('  Mésa   0003 · Otro cliente  '), 'mesa:3');
assert.equal(orders.claveEtiqueta('Mesa 3. Ana'), 'mesa:3');
assert.equal(orders.claveEtiqueta('Mesa 13'), 'etiqueta:mesa 13');
assert.equal(orders.pedidoConEtiqueta([open], 'mesa 03 · Otra persona').id, open.id);
assert.throws(() => orders.resolverEtiqueta('MESA 03 · Otra persona', [open]), /pedido abierto/);
assert.equal(orders.resolverEtiqueta('Mesa 03', [ticket]), 'Mesa 03');
let reserved = orders.nuevoPedido([coffee], 'Mesa 2', 20);
reserved = orders.marcarPartida(reserved, 'todos', 'pagado');
assert.ok(orders.pedidoConEtiqueta([reserved], 'Mesa 02'));
reserved = orders.marcarPartida(reserved, 'todos', 'preparado');
assert.equal(orders.pedidoConEtiqueta([reserved], 'Mesa 02'), null);
const customLabel = orders.nuevoPedido([coffee], '  Ana   López  ', 21);
assert.throws(() => orders.resolverEtiqueta('ana   lópez', [customLabel]), /pedido abierto/);
assert.equal(orders.resolverEtiqueta('', [orders.nuevoPedido([coffee], '', 22)]), '');

// Delivery usa toda la historia, incluso pedidos cerrados, y la vista previa no consume un número.
let deliveryHistory = orders.nuevoPedido([coffee], 'Delivery #12 · Luis', 23);
deliveryHistory = orders.marcarPartida(deliveryHistory, 'todos', 'pagado');
deliveryHistory = orders.marcarPartida(deliveryHistory, 'todos', 'preparado');
assert.equal(orders.siguienteDelivery([deliveryHistory]), 13);
assert.equal(orders.resolverEtiqueta('Delivery · Ana', [deliveryHistory]), 'Delivery #13 · Ana');
assert.equal(orders.resolverEtiqueta('Delivery · Ana', [deliveryHistory]), 'Delivery #13 · Ana');
assert.equal(orders.resolverEtiqueta('Delivery #01 · Otra dirección', [deliveryHistory]), 'Delivery #13 · Otra dirección');
assert.equal(storage.normalizar({ ...storage.vacio(), pedidos: [deliveryHistory] }).siguienteDelivery, 13);
assert.equal(storage.normalizar({ ...storage.vacio(), pedidos: [deliveryHistory], siguienteDelivery: 50 }).siguienteDelivery, 50);
assert.throws(() => storage.normalizar({ ...storage.vacio(), siguienteDelivery: -1 }), /delivery inválida/);

// Las etiquetas duplicadas heredadas se pueden cargar y guardar; los pedidos nuevos se validan antes de escribir.
data.delete(storage.KEY);
data.delete('amor-amor-pos:borrador:v1');
const oldDuplicates = { ...storage.vacio(), pedidos: [orders.nuevoPedido([coffee], 'Mesa 02', 30), orders.nuevoPedido([coffee], 'MESA 2 · Ana', 31)] };
data.set(storage.KEY, JSON.stringify(oldDuplicates));
let labelState = storage.guardarExpediente(storage.cargarExpediente());
assert.equal(labelState.pedidos.length, 2);
const duplicateSnapshot = data.get(storage.KEY);
const duplicateAttempt = JSON.parse(JSON.stringify(labelState));
duplicateAttempt.pedidos.push(orders.nuevoPedido([coffee], 'Mesa 2 · Pedro', 32));
assert.throws(() => storage.guardarExpediente(duplicateAttempt), /etiqueta.*pedido abierto/);
assert.equal(data.get(storage.KEY), duplicateSnapshot);
labelState.pedidos = labelState.pedidos.map(p => orders.marcarPartida(orders.marcarPartida(p, 'todos', 'preparado'), 'todos', 'pagado'));
labelState = storage.guardarExpediente(labelState);
labelState.pedidos.push(orders.nuevoPedido([coffee], 'Mesa 2 · Nueva visita', 32));
labelState = storage.guardarExpediente(labelState);
assert.equal(labelState.pedidos.length, 3);

data.delete(storage.KEY);
let deliveryState = storage.guardarExpediente({ ...storage.vacio(), pedidos: [deliveryHistory] });
const staleDelivery = JSON.parse(JSON.stringify(deliveryState));
deliveryState.pedidos.push(orders.nuevoPedido([coffee], orders.resolverEtiqueta('Delivery · Clara', deliveryState.pedidos, deliveryState.siguienteDelivery), 24));
deliveryState = storage.guardarExpediente(deliveryState);
assert.equal(storage.cargarExpediente().siguienteDelivery, 14);
staleDelivery.pedidos.push(orders.nuevoPedido([coffee], 'Delivery #13 · Otra pestaña', 25));
assert.throws(() => storage.guardarExpediente(staleDelivery), /otra pestaña/);
const reusedDelivery = JSON.parse(JSON.stringify(deliveryState));
reusedDelivery.pedidos.push(orders.nuevoPedido([coffee], 'Delivery #12 · Repetido', 25));
assert.throws(() => storage.guardarExpediente(reusedDelivery), /ya fue utilizado/);
const failedDelivery = JSON.parse(JSON.stringify(deliveryState));
failedDelivery.pedidos.push(orders.nuevoPedido([coffee], 'Delivery #14', 25));
failWrite = true;
assert.throws(() => storage.guardarExpediente(failedDelivery), /QuotaExceeded/);
failWrite = false;
assert.equal(storage.cargarExpediente().siguienteDelivery, 14);
assert.equal(storage.guardarExpediente(failedDelivery).siguienteDelivery, 15);
console.log('✓ Estados por producto, pagos parciales, cortes de Mérida, extras y almacenamiento íntegro verificados.');
